version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usage_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  web:
    build:
      context: .
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/usage_db
      FLASK_ENV: development        # Set Flask to development mode
    volumes:
      - .:/app                      # Mount the current directory to /app in the container
    ports:
      - "5001:5000"                 # Map the container port 5000 to host port 5000
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
